class_name MapCell
extends Resource
## One atomic cell in the bitmap map pipeline.
##
## Map cells are the HOI4/EU4 "province" equivalent: the pixel-accurate
## unit that you see coloured, hover, and click. There are ~1500 of
## them, generated by Voronoi subdivision of the 25 named Regions that
## the game's economy / unrest / relations still run on.
##
## For now, each cell inherits its gameplay state (owner, terrain,
## population, production, unrest) from its parent Region. A later pass
## will migrate those fields to be per-cell so large regions can have
## internal variation (a Macedonian mountain cell can be hostile while
## the capital cell is quiet).

## Integer id. 0 is reserved for "deep water / nothing".
## The RGB channels of the provinces bitmap encode this id directly:
##   R = id        & 0xFF
##   G = (id >>  8) & 0xFF
##   B = (id >> 16) & 0xFF
@export var id: int = 0

## The parent named Region (matches Province.id in WorldData).
@export var region_id: String = ""

## Copied from the parent Region at bake time so the shader's
## terrain layer doesn't have to indirect through the palette.
@export var terrain: int = 0

## Where this cell's label / tooltip anchors, in texture UV space.
@export var center_uv: Vector2 = Vector2.ZERO

## How many pixels this cell covers in the baked bitmap. Useful for
## picking the biggest cell when multiple match at a coarse lookup.
@export var pixel_count: int = 0

## Cell ids that share a border with this one. Used for future
## per-cell simulation and for rendering kingdom-level hulls.
@export var neighbors: PackedInt32Array = PackedInt32Array()


static func from_dict(d: Dictionary) -> MapCell:
	var c: MapCell = MapCell.new()
	c.id = int(d.get("id", 0))
	c.region_id = String(d.get("region_id", ""))
	c.terrain = int(d.get("terrain", 0))
	var uv: Variant = d.get("center_uv", [0.0, 0.0])
	if uv is Array and (uv as Array).size() >= 2:
		c.center_uv = Vector2(float(uv[0]), float(uv[1]))
	c.pixel_count = int(d.get("pixel_count", 0))
	var ns: Variant = d.get("neighbors", [])
	var arr: PackedInt32Array = PackedInt32Array()
	if ns is Array:
		for n in ns:
			arr.append(int(n))
	c.neighbors = arr
	return c


func to_dict() -> Dictionary:
	var ns: Array = []
	for n in neighbors:
		ns.append(n)
	return {
		"id": id,
		"region_id": region_id,
		"terrain": terrain,
		"center_uv": [center_uv.x, center_uv.y],
		"pixel_count": pixel_count,
		"neighbors": ns,
	}
